FROM nvidia/cuda:12.0.1-devel-ubuntu20.04

RUN apt update && apt install -y --no-install-recommends \
  zip \
  git \
  python3 \
  python3-psutil \
  python3-requests \
  pciutils \
  curl && \
  rm -rf /var/lib/apt/lists/*

RUN mkdir -p /root/htpclient
WORKDIR /root/htpclient

RUN git clone https://github.com/BrunoTeixeira1996/agent-python.git && \
  cd agent-python && \
  ./build.sh && \
  mv hashtopolis.zip ../ && \
  cd ../ && rm -rf agent-python

CMD ["bash"]
